//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopMotorcycleRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailProduct
    {
        public string TransactionNumber { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual TransactionService TransactionService { get; set; }
    }
}
