//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopMotorcycleRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionService()
        {
            this.DetailProduct = new HashSet<DetailProduct>();
            this.DetailService = new HashSet<DetailService>();
        }
    
        public string TransactionNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PoliceRegistrationNumber { get; set; }
        public string Damage { get; set; }
        public Nullable<int> TotalServiceCost { get; set; }
        public Nullable<int> TotalProductPrice { get; set; }
        public Nullable<int> TotalCharge { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> ChangeMoney { get; set; }
        public string UserCode { get; set; }
        public string MechanicCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailProduct> DetailProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailService> DetailService { get; set; }
        public virtual Mechanics Mechanics { get; set; }
        public virtual Users Users { get; set; }
    }
}
